name: build macOS, Linux, Windows

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 20

    runs-on: self-hosted

    steps:

      - name: Set up screen (Windows)
        if: runner.os == 'Windows'
        run: |
          Set-DisplayResolution -Width 1920 -Height 1080 -Force
          Get-DisplayResolution

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
            python-version: 3.8

      - name: Install Python dependences
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/easyscience/EasyApp.git@new-easy-app2
          python -m pip install numpy orjson jsbeautifier pytest-image-diff

      - name: Run QML GUI tests
        run: |
          cd EasyExampleApp
          python main.py --testmode

      #- name: Run pytest (compare app images after previous step)
      #  run: pytest
