name: build macOS, Linux, Windows

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 40

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [macos-11, ubuntu-20.04, windows-2019]
        os: [windows-2019]

    steps:
      - name: Cancel previous workflow runs
        uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up non-Python dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -o Acquire::Retries=3 update
          sudo apt-get -o Acquire::Retries=3 install libxcb-xinerama0
          sudo apt-get -o Acquire::Retries=3 install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xfixes0
          sudo apt-get -o Acquire::Retries=3 install libxcb-shape0
          sudo apt-get -o Acquire::Retries=3 install libpulse-mainloop-glib0

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'

#      - name: Upgrade PIP
#        run: python -m pip install --upgrade pip

      - name: Install Python dependences
        run: |
          python -m pip install git+https://github.com/easyscience/EasyApp.git@new-easy-app
          python -m pip install numpy jsbeautifier

      - name: Run GUI tests
        shell: sh #bash
        run: |
          ls
          cd easyExampleApp
          python main.py --testmode
